kind: pipeline
type: docker
name: default
   
workspace:
  path: /home/frappe-user

clone:
  disable: true

steps:
- name: Setup
  image: abhishekbalam/erpnext-testing
  pull: if-not-exists
  commands:
    - echo "here"
    - git clone https://github.com/frappe/frappe --branch $DRONE_BRANCH --depth 1
    - while ! mysqladmin ping -hdatabase --silent; do sleep 1; done
    - mysql -u root -h database -e "SET GLOBAL character_set_server = 'utf8mb4'"
    - mysql -u root -h database -e "SET GLOBAL collation_server = 'utf8mb4_unicode_ci'"
    - mysql -u root -h database -e "CREATE DATABASE test_frappe"
    - mysql -u root -h database -e "CREATE USER 'test_frappe'@'localhost' IDENTIFIED BY 'test_frappe'"
    - mysql -u root -h database -e "GRANT ALL PRIVILEGES ON \`test_frappe\`.* TO 'test_frappe'@'localhost'"
    - mysql -u root -h database -e "UPDATE mysql.user SET Password=PASSWORD('travis') WHERE User='root'"
    - mysql -u root -h database -e "FLUSH PRIVILEGES"

- name: Build
  image: abhishekbalam/erpnext-testing
  pull: if-not-exists
  commands:
    - bench init --skip-assets  --frappe-path ~/frappe --python $(which python3) frappe-bench
    - mkdir ~/frappe-bench/sites/test_site
    - cp ~/erpnext/.travis/site_config.json ~/frappe-bench/sites/test_site/
    - cd frappe-bench;ls
    - sed -i 's/redis_cache:/# redis_cache:/g' Procfile
    - sed -i 's/redis_queue:/# redis_queue:/g' Procfile
    - sed -i 's/watch:/# watch:/g' Procfile
    - sed -i 's/schedule:/# schedule:/g' Procfile
    - sed -i 's/socketio:/# socketio:/g' Procfile
    - sed -i 's/redis_socketio:/# redis_socketio:/g' Procfile
    - bench get-app erpnext 
    - echo "here"
    - bench start &
    - bench --site test_site reinstall --yes

services:
  - name: database
    image: mariadb:10.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

