kind: pipeline
type: docker
name: default
   
steps:
- name: test
  image: abhishekbalam/test1
  commands:
  - whoami; pwd
  - sudo cp -R /drone ~ 
  - cat /home/frappe/site_configs/consumer_db/mariadb.json
  - cat ~/site_configs/consumer_db/mariadb.json
  - cd ~
  - bench init --skip-assets --python $(which python3) frappe-bench
  - mysql -u root -proot -h db -e 'SHOW DATABASES;'

services:
  db:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: root