kind: pipeline
type: docker
name: default
   
workspace:
  path: /home/frappe
  
steps:
- name: test
  image: abhishekbalam/test1
  pull: if-not-exists
  commands:
  - whoami; pwd
  - sudo cp -R /drone ~ 
  - cat /home/frappe/site_configs/consumer_db/mariadb.json
  - cat ~/site_configs/consumer_db/mariadb.json
  - cd ~
  - bench init --skip-assets --python $(which python3) frappe-bench
  - mkdir ~/frappe-bench/sites/test_site  
  - echo $DRONE_BRANCH

services:
  - name: database
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: root