kind: pipeline
type: docker
name: default
   
steps:
- name: test
  image: abhishekbalam/test1
  commands:
  - whoami; pwd
  - sudo cp -R /drone ~ 
  - cat /home/frappe/site_configs/consumer_db/mariadb.json
  - cat ~/site_configs/consumer_db/mariadb.json
  - cd ~
  - bench init --skip-assets --python $(which python3) frappe-bench

